version: "3.8"

services:
  backend:
    image: atvallejo/backend:latest
    ports:
      - "3000:3000"

  frontend:
    image: atvallejo/frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
